version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  # docs:
  #   container_name: docs
  #   build:
  #     context: .
  #     dockerfile: ./docs/Dockerfile
  #   restart: always
  #   ports:
  #     - 3001:3001
  #   networks:
  #     - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
